const os = require('node:os')

var totalmemory = os.totalmem()
var freememory = os.freemem()
console.log('totalmemory:',totalmemory)
console.log('freememory:',freememory)
console.log('availableParallelism:',os.availableParallelism())
console.log('arch:', os.arch())
console.log('homedir:',os.homedir())
console.log("constants:",os.constants)
console.log('cpus:',os.cpus())
console.log('devnull:',os.devNull)
console.log('endianness:',os.endianness())
console.log('getpriority',os.getPriority())
console.log('hostname:',os.hostname())